### ISSUE TITLE
audio - remap

### ISSUE THREAD

**Issue by havi05** [VP-GAMES/LocalizationEditor#1]
When I use the example-files the audioplayer works only until I change the language.
I have Godot in german but when I swich "ingame" to english it is not working.
Sorry for my bad english!
I hope you can help me. (I am new to Godot)

**Comment by VP-GAMES** [comment]
Hi, thx for your bug report, can you upload a small example project with bug? I switch godot to german but, can not reproduce this behaviour. You can also write in German to me i understand german too(Ich verstehe Deutsch! :)

**Comment by havi05** [comment]
Vielen Dank!

Ich habe dein Beispielprojekt benutzt.
Ich habe keine Veränderungen am Code gemacht.
Hier ist ein Video davon: [https://youtu.be/G9Gr9M882b8](url)

**Comment by VP-GAMES** [comment]
Hi, Danke für Dein Einsatz,

ich habe mir das Video angeschaut(hast Dir viel Mühe gegeben), es sieht danach aus als ob die Daten nicht gespeichert wurden, bevor die Scene gestartet wird. Versuche mal bitte den Speichern-Knopf zu drücken und dann die Scene zu starten.
Weitere Möglichkeit dies zu Prüfen: Nach dem Speichern kannst Du unter "Projekt ->  Projekteinstellungen -> Lokalisierung -> Neu zuweisen" schauen ob die Zuweisungen in deinem Projekt gespeichert worden sind. Hier wie die Resourcen in Godot lokalisiert werden: [https://docs.godotengine.org/de/stable/tutorials/i18n/internationalizing_games.html#localizing-resources](https://docs.godotengine.org/de/stable/tutorials/i18n/internationalizing_games.html#localizing-resources). Ich hoffe dort sind die Daten aus dem Plugin.

**Comment by havi05** [comment]
Die start Sprache (Deutsch) funktioniert immer, Russisch fast immer und Englisch nie. (Sobald English ausgewählt wurde funktionieren die anderen Audiodateien (Deutsch und Russisch) nichtmehr.)
 
Sehr merkwürdig! 

Der Wechsel zwischen Deutsch und Russisch funktioniert häufig ohne Probleme.


Ich danke dir sehr, dass du mir bei meinem Sehr komischen Problem hilfst und ich danke dir, dass du so ein hilfreiches Tool programmiert hast.

**Comment by VP-GAMES** [comment]
Habe jetzt hier ein Bugfix eingefuegt, hoffe das es hilft [https://github.com/VP-GAMES/LocalizationEditor/commit/fd12f22f23d8f1e68372012f619a3e42855450fb](https://github.com/VP-GAMES/LocalizationEditor/commit/fd12f22f23d8f1e68372012f619a3e42855450fb) . Es ist noch nicht im AssetStore veröffentlicht(ist im Approve). Wenn Du jetzt schon testen möchtest kannst gerne die aktuelle Version auf Github benutzen. Ich warte dann auf Deine Rückmeldung, danke für Deine Arbeit!

**Comment by havi05** [comment]
Ich habe zu danken!
Ich bin wirklich beeindruckt, wie viel text (scripte) du geschrieben hast !

Leider funktioniert bei mir nur die erste Sprache (deutsch). So bald man wechselt geht keine Audiodatei (auch nicht mehr deutsch)
Es tut mir wirklichleid, dass ich dir nicht noch mehr helfen kann. (Wenn doch einfach schreiben)

Aber vielen Dank für deine Mühe.

**Comment by VP-GAMES** [comment]
Hi, danke für die Rückmeldung! Ich habe noch mal getestet bei mir funktioniert alles einwandfrei. Vieleicht wartest Du nicht lange genug bis die Audiodatei zuende spielt? Probier bitte nochmal mit ein wenig mehr Gedult. Wenn es dann nicht klappt, teile mir bitte Dein benutztes Betriebssystem mit(Ich bin in Linux Ubuntu 20.04 unterwegs)

**Comment by havi05** [comment]
Leider funktioniert es auch nach 10 Sekunden warten nicht. Ich habe Windows 8.1
Könntes du dein Projekt einmal für Windows exportieren?

**Comment by VP-GAMES** [comment]
Nach langem Suchen konnte ich das Verhalten nachstellen, es tritt aber nicht immer auf, anscheinend ist dies ein Godot-Problem.
Hier der Bugreport von mir, mit kleinem Beispielprojekt(kannst gerne da noch mal testen): https://github.com/godotengine/godot/issues/44633 mal schauen was die Godot-Entwickler dazu sagen. Wenn der Bug bestätigt wird, werde ich Dein Bugreport schließen, wenn nicht werde ich natürlich weiter forschen. Nochmals vielen Dank für Deine Mühe und Einsatz!

**Comment by VP-GAMES** [comment]
Der Bug wurde bestätigt: [https://github.com/godotengine/godot/issues/44633](https://github.com/godotengine/godot/issues/44633)

**Comment by havi05** [comment]
Ich danke dir und werde den Report verfolgen.

**Comment by havi05** [comment]
https://github.com/godotengine/godot/issues/42847
Hier hat einer das selbe Problem. (Bug bei Ogg remap)

Ich habe dein Programm nochmals mit wav-Dateien getestet und es funktionierte wunderbar!

Vielen Dank
Gamemap
