### ISSUE TITLE
Error on auto translation

### ISSUE THREAD

**Issue by Lyaaaaaaaaaaaaaaa** [VP-GAMES/LocalizationEditor#10]
**Describe the bug**:
When I start the automatic translation it hangs on after ~15-20%. And if I close Godot and re-opens it, I can see 15-20% has been translated.
I'm using Godot 3.4.3 on Linux.

**Logs**:
There is an infinity of these lines.
```
 core/io/http_client.cpp:326 - Condition "resolving == IP::RESOLVER_INVALID_ID" is true. Returned: ERR_BUG
 core/bind/core_bind.cpp:3216 - Error parsing JSON at line 0: 
 res://addons/localization_editor/scenes/auto_translate/google/LocalizationAutoTranslateGoogle.gd:91 - Invalid get index '0' (on base: 'Nil').
```

**Comment by VP-GAMES** [comment]
Hi, thx for bugreport, please give me more information. It looks like godot can't parse json comming from google translator. Can you give me your text / string that your send to translate.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hi, I made a small project to demonstrate the error. I tried to translate the `localizations.csv` file from english to spanish and it stopped at 18%.
I hope this helps :).
[auto_translation_demo.zip](https://github.com/VP-GAMES/LocalizationEditor/files/8243324/auto_translation_demo.zip)

**Comment by VP-GAMES** [comment]
Hi, it's a bug in godot look here: https://github.com/godotengine/godot/issues/25052
But i can try to implement workaround, to send request after request, not many requests at the same time.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
Hi, I didn't know that. At least the bug is now identified.

**Comment by VP-GAMES** [comment]
In this moment, i implement a workaround

**Comment by VP-GAMES** [comment]
Here is my workaround: https://github.com/VP-GAMES/LocalizationEditor/commit/bc4754c17e93b21c6fd7e2a913e103da8aaffae2
Please try it and give me feedback to close this issue.

**Comment by Lyaaaaaaaaaaaaaaa** [comment]
It works very well. Though, if you add a new key and try to translate again, it will hang at 18% and won't translate the empty keys.
I also noticed there is problems saving the .CSV if you have `"` or `,` in the strings (Maybe you want me to open another issue for this one).

**Comment by VP-GAMES** [comment]
Open new issue, and please explain the issue
