### ISSUE TITLE
ERROR: The identifier "LocalizationKeys" isn't declared in the current scope

### ISSUE THREAD

**Issue by NickHatBoecker** [VP-GAMES/LocalizationEditor#11]
Trying to start my game I get the following error:

`ERROR: The identifier "LocalizationKeys" isn't declared in the current scope`

Looks like `LocalizationKeys` was [named differently](https://github.com/VP-GAMES/LocalizationEditor/commit/1d89d05598d2ddc4a79f3f716c172737eafac8a8) before. Maybe it was accidentally deleted at some point?

**Comment by VP-GAMES** [comment]
Hi, resave your localization. Then start a game. Check file res//:localization/LocalizationKeys.gd
Here the examle https://github.com/VP-GAMES/LocalizationEditor/blob/main/localization/LocalizationKeys.gd
