### ISSUE TITLE
[Featurerequest] - Translation (self/google)

### ISSUE THREAD

**Issue by havi05** [VP-GAMES/LocalizationEditor#2]
Hallo,

kannst du bei automatisch übersätzten Sprachen die selbst übersätzten **_Teile_** in einer Farbe markieren?
Alternativ die noch nicht selbst übersätzten **_Teile markieren_** oder Ein-/Ausschaltbar.

Ich danke dir sehr,
Gamemap

Neu = **_italic / bold_**

**Comment by VP-GAMES** [comment]
Hi, da musste ich überlegen was für eine Farbe und es müsste extra markiert werden, Überlege es mir. Normalerweise macht es keinen Sinn, da es über ein Versionierungssystem wie Git abgedeckt werden kann.

**Comment by havi05** [comment]
Ich kenne mich leider mit so etwas wie Git nicht aus. 
Damit wir uns nicht missverstehen: Kann man alle selbst übersätzten Sprachenteile in einer Farbe (z.B. Grün) darstellen, damit man weiß, was noch zu kontrollieren (beim Googleübersätzer)/ übersätzen ist?

Vielen Dank, dass du mir hilfst
Gamemap

**Comment by VP-GAMES** [comment]
Hi Gamemap, sorry das ich länger nicht reagiert habe, schrieb ein anderes [Plugin](https://github.com/VP-GAMES/DialogueEditor), wollte mich nicht ablenken. 
Benutze am besten [Git](https://git-scm.com/) dafür, hier ein kleiner Einstieg: https://rogerdudler.github.io/git-guide/index.de.html

Beste Grüße

VP_GAMES

**Comment by havi05** [comment]
Danke, ich werde es mir anschauen.
