### ISSUE TITLE
Translations with space (e.g. FileDialog)

### ISSUE THREAD

**Issue by havi05** [VP-GAMES/LocalizationEditor#3]
Ich möchte den FileDialog übersäzen, aber dazu muss ich unter keys Create Folder eintragen. Die Lücke wird aber beim Laden entfernt. Kann ich das verhindern?

Gamemap

P.S. Vielleicht kann man ändern, dass .po Dateien entfernt werden.
       https://github.com/godotengine/godot/tree/master/editor/translations    (zum Beispiel de.po)

**Comment by VP-GAMES** [comment]
Hi, Gamemap in moment leider nicht! Ich habe es extra so gebaut, damit die ganzen Konstanten vernünftig exportiert werden können. Aus deinen Keys wird LocalizationManagerKeys.gd erzeugt dort stehen dan die ganzen Zuordnungen. Beschreib bitte dein Problem besser, ich versuche es zu lösen.

**Comment by havi05** [comment]
Ich möchte beispielsweise den Text "Create Folder" übersätzen. Man muss das in die keys Spalte schreiben. Die keys werden zum leichteren benutzen als Variable gespeichert. (auch mit Leerzeichen und das Leerzeichen mag Godot nicht)
Kann man das Hinzufügen dieser einen Variable verhindern? (oder Kommentieren, ...)

Erstaunlicherweise geht es mit "Path:" . (Variable mit Doppelpunkt am Ende)

**Comment by VP-GAMES** [comment]
Hi Gamemap, habe es jetzt verbessert. [Hier der Fix](https://github.com/VP-GAMES/LocalizationEditor/commit/7f0129fdaa9702c2cfc6a83cec8a433237714c2a). Danke für dein Einsatz!
