### ISSUE TITLE
Change translation language KEYS (with spaces)

### ISSUE THREAD

**Issue by havi05** [VP-GAMES/LocalizationEditor#4]
Hallo,

ich danke dir, dass du das Feature einprogrammiert hast, leider funktioniert das Übersätzen der KEYS mit Lücke noch nicht. Es wird bei mir immer nur die letzte Sprache (ganz links im Localisationsmenü) übersätzt. 
`TranslationServer.set_locale("en") ODER TranslationServer.set_locale("de")` übersätzt nur die mit Lücke <ins>**nicht**</ins>. (ich nutze diesen Code um eine Standartsprache leicht zu definieren / ändern)

Ich hoffe du kannst das einfach lösen,
Gamemap

**Comment by VP-GAMES** [comment]
Hi Gamemap,
die KEYS dürften eigentlich keine Leerzeichen enthalten es sind keine echten Werte, es sind Schlüsselwerte. Hinter einem KEY in Kombination mit der Sprache verbirgt sich die Übersetzung. Die KEYS können nicht übersetzt werden, die müssen immer gleich bleiben. Bispiel: MEIN_KEY => My key(en), Mein Schlüssel(de), Мой ключь(ru) für alle Sprachen ist der Schlüsselwert gleich MEIN_KEY. Dieser darf nicht übersetzt werden, der ist immer konstant!

Grüße, VP_GAMES

**Comment by havi05** [comment]
Ich habe mich leider nicht genau formuliert, deswegen ist ein Missverständnis aufgetreten. Ich möchte nicht die KEYS übersätzen, sondern bei dem KEY z.B. `Create Folder` die Übersätzungssprache ändern. Diese Übersätzung hat nur bei den zugewiesenen KEYS nicht funktioniert, die eine Lücke im Wort haben. Um bei einem FileDialog die Sprache zu ändern muss man den oben genannten KEY eintragen. (Mit einer .csv Datei alleine funktioniert es, aber ich möchte lieber dein Plugin nutzen)

Gamemap

**Comment by VP-GAMES** [comment]
Ich glaube, habe jetzt die Problematik verstanden, mal sehen ob es eine einfache Lösung dafür gibt.

**Comment by havi05** [comment]
Danke

**Comment by VP-GAMES** [comment]
So, ich denke das soll es gewesen sein, wenn ich Dich richtig verstanden habe: https://github.com/VP-GAMES/LocalizationEditor/commit/300e5872a3393c2864cda12bd51b9c9ff71ca134

**Comment by havi05** [comment]
Leider funktioniert es immer noch nicht. Wenn du das ließt, bitte öffne es wieder. 

**Schritte und Beobachtungen:**
Ich habe es nun ausgetestet und Erstaunlicherweise startet es immer auf deutsch.
Ich habe den neuen KEY hinzugefügt und er übersätzt `Create Folder` auf deutsch.
Wenn ich eine andere Sprache auswähle übersätzt er es nicht mehr.

**Besonders:**
Wenn ich die deutsche Übersätzung weglasse übersätzt er es in die anderen sprachen.

**Link:**
Ich habe zu deinem Demo den FileDialog hinzugefügt, damit du es testen kannst.
Wenn du beim letzten KEY `Create Folder` die deutsche Übersätzung wegnimmst, funktioniert alles. (zumindest bei mir)
https://github.com/Gamemap/FileDialog

Gamemap

**Comment by VP-GAMES** [comment]
Hi ich konnte Dein Problem nicht nachstellen! Bitte trage in das Window Title Feld den KEY: Create Folder ein(da steht _Datei speichern_, was ja nicht sein darf wenn es übersetzt werden soll) und teste. Bitte Dich um Rückmeldung, hier ein Screenshot:
![PROB](https://user-images.githubusercontent.com/74808066/107478551-f163da80-6b79-11eb-94f0-b331acaa03a8.png)

**Comment by havi05** [comment]
Ich habe mit grün Markiert, was übersätzt werden soll.  (Der Button : `Create Folder`)
Ich hoffe das hilft dir mein Problem nachzustellen.

Ein Godot-Develpoer hat mir gesagt, das man die Felder mit den KEYS aus https://github.com/godotengine/godot/tree/master/editor/translations (zum Beispiel de.po) (Hier der KEY `Create Folder`) übersätzen kann.

![107478551-f163da80-6b79-11eb-94f0-b331acaa03a8](https://user-images.githubusercontent.com/71942164/107489880-71de0780-6b89-11eb-8de4-909851291a80.png)

**Comment by VP-GAMES** [comment]
Kann leider nicht nachstellen, hier die Screenshots alles wird übersetzt:
![Screenshot from 2021-02-10 10-41-33](https://user-images.githubusercontent.com/74808066/107492742-144bba00-6b8d-11eb-9107-7f44a2792e04.png)
![Screenshot from 2021-02-10 10-41-53](https://user-images.githubusercontent.com/74808066/107492755-1746aa80-6b8d-11eb-8c7e-55eaf0d4f840.png)
![Screenshot from 2021-02-10 10-42-04](https://user-images.githubusercontent.com/74808066/107492767-19106e00-6b8d-11eb-9a7e-ca4467f18994.png)

**Comment by havi05** [comment]
Ok, ich schau nochmal bei mir nach.

**Comment by havi05** [comment]
Leider funktioniert es bei mir nicht. Ich wundere mich, warum es automatisch auf deutsch startet. `TranslationServer.set_locale("en")`übersätzt alles bis auf den FileDialog. Ich vermute, dass es mit dem Starten auf deutsch zu tun haben könnte. (Da wenn es weggelassen wird, es richtig übersätzt.) Es passiert auch, wenn ich z.B. `Path:` übersätzte. (Ich glaube, das das vorher ging.)

Gamemap

**Comment by VP-GAMES** [comment]
Wir können höchstens noch in Discord schauen wenn Du magst, hier https://discord.gg/Tr7Ma6E mein name: Vladimir RU/DE/EN#0656

**Comment by havi05** [comment]
Tut mir leid, aber ich habe kein Discord (wegen Datenschutzproblemen)

Ich kann dir nur Anydesk anbieten. (Dektop übertragung)

**Comment by havi05** [comment]
Startet es auch bei dir immer in einer bestimmten Sprache? (Systemsprache?)

**Comment by havi05** [comment]
Ich habe es nun auf einem anderen Betriebsystem (Linux  Mint als Webseite Link unten) ausprobiert und es funktioniert. Weißt du, warum er es auf deutsch startet? Ich glaube da ist ein problem (zumindest bei Windows). Ich versuche noch genaueres herraus zu finden.

Gamemap

https://www.onworks.net/os-distributions (da gibt es sicher auch windows zum testen)

**Comment by havi05** [comment]
Ich will versuchen den Editor zurück zu setzen. Dazu möchte ich alle Godot-Ordner löschen. (Godot Hauptspeicher und Godot bei AppData (windows)). 

Weißt du, ob irgend etwas dabei kaputt gehen kann?

**Comment by VP-GAMES** [comment]
Es wir die Systemsprache genommen.

**Comment by havi05** [comment]
> 
> 
> Es wir die Systemsprache genommen.

Danke

Ich werde mal den Launcher/Editor resetten.

**Comment by havi05** [comment]
Wo wird die Systemsprache erkannt?

**Comment by VP-GAMES** [comment]
Der TranslationServer macht das, meine ich, wenn dieser als Singleton instantiert wird. Das wird direkt von der Engine so geregelt.
Du kannst gerne eigenen Singleton(AutoLoad) definieren und dort die Sprache TranslationServer.set_locale("en") festlegen.

**Comment by havi05** [comment]
Ok, hast du Godot auf deutsch? (Ich versuche herraus zu finden warum es nicht funktioniert) Ich probiere Windows auf englisch.

**Comment by havi05** [comment]
Bei mir übersätzt er nur Teile. (Sehr merkwürdig) Windows englisch
![Capture](https://user-images.githubusercontent.com/71942164/107579711-d8990a80-6bf5-11eb-9ead-5f2060691b41.PNG)

**Comment by havi05** [comment]
Ich habe es nun ohne das Plugin Versucht und habe festgestellt, dass es den FileDialog nur einmalig beim Starten übersätzt wurde (Beim Plugin ging das übersätzen nur nicht in der Systemsprache)
Ich versuche einen Bug report dazu zu erstellen (leider habe ich nicht viele Informationen)
Hier noch ein Video:

https://user-images.githubusercontent.com/71942164/107584808-6b897300-6bfd-11eb-9ad0-d4196030dec4.mp4

**Comment by VP-GAMES** [comment]
Super, danke für Dein Einsatz. Ich habe selber einige Bugs(Audio/Video) bereits zum TranslationServer gemeldet! Melde Dich gerne wider :+1:

**Comment by havi05** [comment]
Das Übersätzungsproblem wird nun behoben. (https://github.com/godotengine/godot/pull/46735)
