### ISSUE TITLE
Godot 3.3 does not close when LocalizationEditor is active

### ISSUE THREAD

**Issue by paacardoso** [VP-GAMES/LocalizationEditor#6]
Godot 3.3 does not close when using LocalizationEditor is active.
If I disable it in the project settings, Godot closes properly.
I'm using the latest version (1.3.3)
This is happening in Ubuntu 20.04. Not sure if it happens also in windows.

**Comment by VP-GAMES** [comment]
Thank you for your report, have you some errors in console? Can you describe how to reproduce this behavior.
I use also Ubuntu 20.04.2 LTS, with Godot 3.3 but i have no problems. Please give me more information.

**Comment by paacardoso** [comment]
Well,
Here it is the output when running godot from the console.
![image](https://user-images.githubusercontent.com/11839951/117956547-0d118500-b311-11eb-84a6-40737ec2a41e.png)

Also, i'm attaching the mono log file
[2021-05-12_10.53.58_18534.log](https://github.com/VP-GAMES/LocalizationEditor/files/6465333/2021-05-12_10.53.58_18534.log)

I don't see anything related to LocalizationEditor, but if I don't disable it in the plugins, Godot will not close and I have to kill it in System Monitor
![image](https://user-images.githubusercontent.com/11839951/117957055-9032db00-b311-11eb-96d4-058960523f73.png)

Also, I'm currently using mono (C#) instead of GDScript. Not sure if this can be a problem or not.

**Comment by VP-GAMES** [comment]
Ok, I use the the GDScript version of Godot 3.3 and have no problems. I try to use mono (c#) based version in few days and fixing the problem if possible, you can also test with the normal Godot version and give your feedback.

**Comment by paacardoso** [comment]
Well, i'm getting mixed results.
I've created a GDScript project, and I did not get any problems.
Then I also created a new C# project and I did not get any error also.
These two projects we're created with Godot 3.3 for C# and when I close Godot, it closed properly.

But, when I did come back to my project, I did find the that when I create a new scene and save it, I get the following error:

![image](https://user-images.githubusercontent.com/11839951/118161470-8abfb880-b417-11eb-8f7f-36d1ad895f3e.png)

When I disable LocalizationEditor  in project settings plugins, this error does not occur.
So, perhaps it has to do with something that you're doing in this situation.

**Comment by VP-GAMES** [comment]
Thank you for you deep debuging. I try it out, but I have no errors. Can you clone git repository [LocalizationEditor](https://github.com/VP-GAMES/LocalizationEditor) and open it in your Godot versions or send me example project.

**Comment by VP-GAMES** [comment]
Hi, again! I hope i found the solution [here](https://godotengine.org/qa/83957/file-must-be-opened-before-use). Today, I try to make a bugfix and hope it is the solution for this problem

**Comment by paacardoso** [comment]
Hi,
Not quite yet. The problem still persists.
However, I think I found part of the "problem" ...
The following two lines, that are storing strings, are still outputing errors to the console:

file.store_string(source_code) (in /addons/localization_editor/model/LocalizationData.gd -> line 110)
file.store_string(source_code) (in /addons/localization_editor/model/LocalizationData.gd -> line 141)

I've comment those two lines and the errors in the console disappeared.
Not sure why, because your code seems ok. But, i'm not very good at gdscript...

However, even with those two lines commented, I still have to kill the process to close Godot.

**Comment by VP-GAMES** [comment]
Please can you comment out this lines and try again:
/addons/localization_editor/model/LocalizationData.gd -> line 69
/addons/localization_editor/model/LocalizationData.gd -> line 70

```
func save_data_translations() -> void:
	_save_data_translations_csv()
	#_save_data_translations_keys()      <= COMMENT OUT
	#_save_data_translations_placeholders()    <= COMMENT OUT
	_save_data_translations_to_project_settings()
	_editor.get_editor_interface().get_resource_filesystem().scan()
```

**Comment by paacardoso** [comment]
Hi again,
Those two lines did not solve the problem.
However, i found out that commenting the last one (line 72), Godot closes normally :)

```
func save_data_translations() -> void:
	_save_data_translations_csv()
	#_save_data_translations_keys()      <= SEEMS OK
	#_save_data_translations_placeholders()    <= SEEMS OK
	_save_data_translations_to_project_settings()
	_editor.get_editor_interface().get_resource_filesystem().scan()     <= SOME PROBLEM HERE
```

So, I think the problem is with line 72 ...

**Comment by VP-GAMES** [comment]
Hi, i create a bugfix (version 1.3.7) [here is it](https://github.com/VP-GAMES/LocalizationEditor/commit/c84ea10b728741879d1607778245226993a02e5e). Please give me feedback, if it works i close the issue. Thank you big for your commitment.

**Comment by paacardoso** [comment]
Hi Again,

OK. Now it's "working". Godot now closes properly, and I don't have to close it in process manager (or system monitor).
However, I still notice the following messages:

![image](https://user-images.githubusercontent.com/11839951/118726940-eb8d2d80-b829-11eb-8979-bc691f875d53.png)

These message are visible in the console when I run my project. They do not cause any issue. At least I didn't find any.
I run Godot with the --verbose flag, but there isn't any more info besides on what is in the screenshot.
For me, those messages are not a problem. Now I can have the addon allways active and Godot closes normally.

BTW, nice job with LocalizationEditor. It is a very nice addon and I'm going to use it in my current projects.
So, Thank You very much :)

**Comment by VP-GAMES** [comment]
Hi, OK I thank you very much to. Have fun with the plugin ;). It was nice to solve this problem with you. Good work. Good luck and continued success!
