### ISSUE TITLE
LocalizationEditorDialogFile problems.

### ISSUE THREAD

**Issue by rambda** [VP-GAMES/LocalizationEditor#8]
For LocalizationEditorDialogFile.tscn:

I think the `mode` inherited from FileDialog should be `Open File`, otherwise when opening the file, it will ask whether to overwrite the file.

The `resizable` should be checked too, otherwise it's unusable on 4K monitor.

Also, this is not a bug, but if the editor language is set to CJKV characters, any text of WindowDialog and any node that inherits from it will become the corresponding language. However, since the default font of Godot project is a Bitmap font that does not contain Unicode characters, all these characters will be blank. LocalizationEditorDialogFile is no exception. OK... i think i'll just open an issue from Godot's repo and mention this plugin.

**Comment by VP-GAMES** [comment]
Fixed in this commit: https://github.com/VP-GAMES/LocalizationEditor/commit/0209a33acc20d6e6da43ef41426c844c88a91fd6
